// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4AvuSWipP1_TxAyc5T_L4NyBjJIPQv4w',
    appId: '1:33127114604:web:88dbc492dd149a1a797549',
    messagingSenderId: '33127114604',
    projectId: 'flutter-firebase-test-e1bcc',
    authDomain: 'flutter-firebase-test-e1bcc.firebaseapp.com',
    storageBucket: 'flutter-firebase-test-e1bcc.appspot.com',
    measurementId: 'G-SX0B4808W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhQjLJ1dXdXxQS_0m28vK4Lld7U1s5fGE',
    appId: '1:33127114604:android:32a727d72a4afc2c797549',
    messagingSenderId: '33127114604',
    projectId: 'flutter-firebase-test-e1bcc',
    storageBucket: 'flutter-firebase-test-e1bcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkBZfpKsbirJKo83raHzgAvsNN1QquhjE',
    appId: '1:33127114604:ios:9f10a68a644f0a5d797549',
    messagingSenderId: '33127114604',
    projectId: 'flutter-firebase-test-e1bcc',
    storageBucket: 'flutter-firebase-test-e1bcc.appspot.com',
    iosClientId: '33127114604-ker25ul9qmqmcmliil0bsek3l6j5c55v.apps.googleusercontent.com',
    iosBundleId: 'com.tamergunes.flutterFirebase',
  );
}
